-- Shared short-lived holds so multiple API workers do not promise the same
-- staff slot or overlapping room stay while customers are confirming.

create table if not exists booking_slot_hold (
  hold_id bigint generated by default as identity primary key,
  company_id int not null references companies(company_id) on delete cascade,
  resource_kind text not null check (resource_kind in ('SLOT', 'ROOM')),
  service_type text not null,
  holder_key text not null,
  slot_date date,
  slot_time time,
  end_time time,
  staff_id int,
  room_type text,
  check_in_date date,
  check_out_date date,
  expires_at timestamptz not null
);

alter table booking_slot_hold add column if not exists end_time time;
alter table booking_slot_hold add column if not exists staff_id int;

create index if not exists booking_slot_hold_expiry_idx on booking_slot_hold(expires_at);
drop index if exists booking_slot_hold_slot_idx;
create index if not exists booking_slot_hold_slot_idx
  on booking_slot_hold(company_id, staff_id, slot_date, slot_time, end_time)
  where resource_kind = 'SLOT';
create index if not exists booking_slot_hold_room_idx
  on booking_slot_hold(company_id, room_type, check_in_date, check_out_date)
  where resource_kind = 'ROOM';

alter table booking_slot_hold enable row level security;
revoke all on table booking_slot_hold from public, anon, authenticated;

drop function if exists public.acquire_booking_hold(
  int, text, text, text, date, time, text, date, date, int, int
);

create or replace function public.acquire_booking_hold(
  p_company_id int,
  p_resource_kind text,
  p_service_type text,
  p_holder_key text,
  p_slot_date date default null,
  p_slot_time time default null,
  p_end_time time default null,
  p_staff_id int default null,
  p_room_type text default null,
  p_check_in_date date default null,
  p_check_out_date date default null,
  p_capacity int default 1,
  p_exclude_booking_id int default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_kind text := upper(btrim(p_resource_kind));
  v_count int;
begin
  if nullif(btrim(p_holder_key), '') is null then
    raise exception 'holder_key is required' using errcode = 'P0001';
  end if;
  delete from booking_slot_hold where expires_at <= now();

  if v_kind = 'SLOT' then
    if p_slot_date is null or p_slot_time is null or p_end_time is null
       or p_end_time <= p_slot_time or p_staff_id is null then
      raise exception 'slot_date, staff_id, and a valid slot interval are required' using errcode = 'P0001';
    end if;
    perform pg_advisory_xact_lock(hashtextextended(
      p_company_id::text || ':hold:staff:' || p_staff_id::text, 0
    ));
    if exists (
      select 1 from booking_slot_hold
      where company_id = p_company_id and resource_kind = 'SLOT'
        and staff_id = p_staff_id and slot_date = p_slot_date
        and slot_time < p_end_time and p_slot_time < end_time
        and holder_key <> p_holder_key and expires_at > now()
    ) then
      return false;
    end if;
    delete from booking_slot_hold
      where company_id = p_company_id and resource_kind = 'SLOT'
        and holder_key = p_holder_key;
    insert into booking_slot_hold(
      company_id, resource_kind, service_type, holder_key,
      slot_date, slot_time, end_time, staff_id, expires_at
    ) values (
      p_company_id, 'SLOT', upper(p_service_type), p_holder_key,
      p_slot_date, p_slot_time, p_end_time, p_staff_id,
      now() + interval '15 minutes'
    );
    return true;
  elsif v_kind = 'ROOM' then
    if nullif(btrim(p_room_type), '') is null or p_check_in_date is null
       or p_check_out_date is null or p_check_out_date <= p_check_in_date then
      raise exception 'valid room_type/check-in/check-out are required' using errcode = 'P0001';
    end if;
    perform pg_advisory_xact_lock(hashtextextended(
      p_company_id::text || ':hold:room:' || lower(p_room_type), 0
    ));
    select
      (select count(*) from boarding_booking b
       where b.company_id = p_company_id and lower(b.room_type) = lower(p_room_type)
         and b.booking_status in ('Pending', 'Scheduled')
         and (p_exclude_booking_id is null or b.boarding_booking_id <> p_exclude_booking_id)
         and b.check_in_date < p_check_out_date and p_check_in_date < b.check_out_date)
      +
      (select count(*) from booking_slot_hold h
       where h.company_id = p_company_id and h.resource_kind = 'ROOM'
         and lower(h.room_type) = lower(p_room_type)
         and h.holder_key <> p_holder_key and h.expires_at > now()
         and h.check_in_date < p_check_out_date and p_check_in_date < h.check_out_date)
    into v_count;
    if v_count >= greatest(p_capacity, 1) then
      return false;
    end if;
    delete from booking_slot_hold
      where company_id = p_company_id and resource_kind = 'ROOM'
        and holder_key = p_holder_key;
    insert into booking_slot_hold(
      company_id, resource_kind, service_type, holder_key,
      room_type, check_in_date, check_out_date, expires_at
    ) values (
      p_company_id, 'ROOM', 'BOARDING', p_holder_key,
      p_room_type, p_check_in_date, p_check_out_date, now() + interval '15 minutes'
    );
    return true;
  end if;
  raise exception 'resource_kind must be SLOT or ROOM' using errcode = 'P0001';
end;
$$;

revoke all on function public.acquire_booking_hold(int, text, text, text, date, time, time, int, text, date, date, int, int)
  from public, anon, authenticated;
grant execute on function public.acquire_booking_hold(int, text, text, text, date, time, time, int, text, date, date, int, int)
  to service_role;

notify pgrst, 'reload schema';
