-- Company business hours and dates on which booking services are unavailable.
-- This migration creates the tables only; it does not insert schedule data.

create table if not exists public.company_closed_dates (
  closed_date_id bigint generated by default as identity primary key,
  company_id bigint not null
    references public.companies(company_id) on delete cascade,
  closed_date date not null,
  reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint company_closed_dates_company_date_unique
    unique (company_id, closed_date),
  constraint company_closed_dates_reason_not_blank
    check (reason is null or length(btrim(reason)) > 0)
);

create index if not exists company_closed_dates_lookup_idx
  on public.company_closed_dates (company_id, closed_date);

alter table public.company_closed_dates enable row level security;

drop policy if exists company_closed_dates_select_own
  on public.company_closed_dates;

create policy company_closed_dates_select_own
  on public.company_closed_dates
  for select
  using (company_id = current_company_id());

-- Recurring weekly business hours.
-- day_of_week follows PostgreSQL extract(dow): 0 = Sunday, 6 = Saturday.

create table if not exists public.company_business_hours (
  business_hour_id bigint generated by default as identity primary key,
  company_id bigint not null
    references public.companies(company_id) on delete cascade,
  day_of_week smallint not null
    check (day_of_week between 0 and 6),
  open_time time,
  close_time time,
  is_closed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint company_business_hours_company_day_unique
    unique (company_id, day_of_week),
  constraint company_business_hours_valid_times
    check (
      (is_closed and open_time is null and close_time is null)
      or
      (
        not is_closed
        and open_time is not null
        and close_time is not null
        and close_time > open_time
      )
    )
);

create index if not exists company_business_hours_lookup_idx
  on public.company_business_hours (company_id, day_of_week);

alter table public.company_business_hours enable row level security;

drop policy if exists company_business_hours_select_own
  on public.company_business_hours;

create policy company_business_hours_select_own
  on public.company_business_hours
  for select
  using (company_id = current_company_id());

-- Atomically replace both parts of a company's availability configuration.
-- The Express backend validates and normalizes these JSON arrays before calling.

create or replace function public.replace_company_availability(
  p_company_id bigint,
  p_business_hours jsonb,
  p_closed_dates jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.company_business_hours
  where company_id = p_company_id;

  insert into public.company_business_hours (
    company_id, day_of_week, open_time, close_time, is_closed
  )
  select
    p_company_id,
    item.day_of_week,
    item.open_time::time,
    item.close_time::time,
    item.is_closed
  from jsonb_to_recordset(coalesce(p_business_hours, '[]'::jsonb))
    as item(day_of_week smallint, open_time text, close_time text, is_closed boolean);

  delete from public.company_closed_dates
  where company_id = p_company_id;

  insert into public.company_closed_dates (company_id, closed_date, reason)
  select p_company_id, item.closed_date::date, nullif(btrim(item.reason), '')
  from jsonb_to_recordset(coalesce(p_closed_dates, '[]'::jsonb))
    as item(closed_date text, reason text);
end;
$$;

revoke all on function public.replace_company_availability(bigint, jsonb, jsonb)
  from public, anon, authenticated;
grant execute on function public.replace_company_availability(bigint, jsonb, jsonb)
  to service_role;
