-- Install after the base schema. It hardens the remaining multi-row CRUD
-- operations and records every exceptional points correction.

create table if not exists loyalty_points_adjustment (
  adjustment_id bigint generated by default as identity primary key,
  company_id int not null references companies(company_id) on delete cascade,
  loyalty_id int not null references loyaltymember(loyalty_id) on delete cascade,
  changed_by_account_id int references accounts(account_id) on delete set null,
  old_balance int not null,
  new_balance int not null,
  reason text not null,
  created_at timestamptz not null default now(),
  constraint loyalty_points_adjustment_reason_not_blank check (length(btrim(reason)) > 0),
  constraint loyalty_points_adjustment_balances_nonnegative check (old_balance >= 0 and new_balance >= 0)
);

create index if not exists loyalty_points_adjustment_company_loyalty_idx
  on loyalty_points_adjustment(company_id, loyalty_id, created_at desc);

alter table loyalty_points_adjustment enable row level security;
drop policy if exists tenant_select on loyalty_points_adjustment;
create policy tenant_select on loyalty_points_adjustment for select
  using (company_id = current_company_id());

create or replace function adjust_loyalty_points(
  p_company_id int,
  p_loyalty_id int,
  p_new_balance int,
  p_reason text,
  p_account_id int
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_member loyaltymember%rowtype;
  v_tier text;
begin
  if p_new_balance < 0 or nullif(btrim(p_reason), '') is null then
    raise exception 'A non-negative balance and reason are required' using errcode = 'P0001';
  end if;
  select * into v_member from loyaltymember
    where company_id = p_company_id and loyalty_id = p_loyalty_id for update;
  if not found then raise exception 'Loyalty member not found' using errcode = 'P0002'; end if;

  v_tier := case when p_new_balance >= 1200 then 'Platinum'
    when p_new_balance >= 700 then 'Gold'
    when p_new_balance >= 300 then 'Silver'
    else 'Bronze' end;
  update loyaltymember set points_balance = p_new_balance, tier = v_tier
    where company_id = p_company_id and loyalty_id = p_loyalty_id;
  insert into loyalty_points_adjustment(
    company_id, loyalty_id, changed_by_account_id, old_balance, new_balance, reason
  ) values (
    p_company_id, p_loyalty_id, p_account_id, v_member.points_balance, p_new_balance, btrim(p_reason)
  );
  return jsonb_build_object(
    'loyalty_id', p_loyalty_id, 'points_balance', p_new_balance,
    'tier', v_tier, 'adjustment_reason', btrim(p_reason)
  );
end;
$$;

create or replace function update_account_guarded(
  p_company_id int,
  p_account_id int,
  p_role text,
  p_status text
)
returns accounts
language plpgsql
security definer
set search_path = public
as $$
declare
  v_target accounts%rowtype;
  v_result accounts%rowtype;
begin
  perform account_id from accounts where company_id = p_company_id order by account_id for update;
  select * into v_target from accounts
    where company_id = p_company_id and account_id = p_account_id;
  if not found then raise exception 'Account not found' using errcode = 'P0002'; end if;
  if v_target.role = 'manager' and v_target.account_status = 'active'
    and (coalesce(p_role, v_target.role) <> 'manager' or coalesce(p_status, v_target.account_status) <> 'active')
    and (select count(*) from accounts where company_id = p_company_id and role = 'manager' and account_status = 'active') <= 1
  then
    raise exception 'The company must keep at least one active manager account' using errcode = 'P0001';
  end if;
  update accounts set role = coalesce(p_role, role), account_status = coalesce(p_status, account_status)
    where company_id = p_company_id and account_id = p_account_id returning * into v_result;
  return v_result;
end;
$$;

create or replace function delete_account_guarded(p_company_id int, p_account_id int)
returns accounts
language plpgsql
security definer
set search_path = public
as $$
declare
  v_target accounts%rowtype;
begin
  perform account_id from accounts where company_id = p_company_id order by account_id for update;
  select * into v_target from accounts
    where company_id = p_company_id and account_id = p_account_id;
  if not found then raise exception 'Account not found' using errcode = 'P0002'; end if;
  if v_target.role = 'manager' and v_target.account_status = 'active'
    and (select count(*) from accounts where company_id = p_company_id and role = 'manager' and account_status = 'active') <= 1
  then
    raise exception 'The company must keep at least one active manager account' using errcode = 'P0001';
  end if;
  delete from accounts where company_id = p_company_id and account_id = p_account_id;
  return v_target;
end;
$$;

revoke all on function adjust_loyalty_points(int, int, int, text, int) from public, anon, authenticated;
revoke all on function update_account_guarded(int, int, text, text) from public, anon, authenticated;
revoke all on function delete_account_guarded(int, int) from public, anon, authenticated;
grant execute on function adjust_loyalty_points(int, int, int, text, int) to service_role;
grant execute on function update_account_guarded(int, int, text, text) to service_role;
grant execute on function delete_account_guarded(int, int) to service_role;

alter table redemption add column if not exists cancelled_date date;
alter table redemption add column if not exists cancelled_time time;
alter table redemption add column if not exists cancellation_reason text;

create or replace function cancel_approved_redemption(
  p_company_id int,
  p_redemption_id int,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_payment payment%rowtype;
  v_redemption redemption%rowtype;
  v_member loyaltymember%rowtype;
  v_balance int;
  v_tier text;
begin
  if nullif(btrim(p_reason), '') is null then
    raise exception 'A cancellation reason is required' using errcode = 'P0001';
  end if;
  -- Same global lock order as request/decide/verify: payment, redemption, member.
  select * into v_payment from payment
    where company_id = p_company_id and redemption_id = p_redemption_id for update;
  if not found then raise exception 'Linked payment not found' using errcode = 'P0002'; end if;
  if v_payment.status not in ('Pending', 'Unpaid', 'Cancelled') then
    raise exception 'A redemption on a completed payment must be refunded through the payment refund flow'
      using errcode = 'P0001';
  end if;
  select * into v_redemption from redemption
    where company_id = p_company_id and redemption_id = p_redemption_id for update;
  if not found or v_redemption.status <> 'Approved' then
    raise exception 'Only an approved redemption can be cancelled' using errcode = 'P0001';
  end if;
  select * into v_member from loyaltymember
    where company_id = p_company_id and loyalty_id = v_redemption.loyalty_id for update;
  if not found then raise exception 'Loyalty member not found' using errcode = 'P0002'; end if;

  v_balance := v_member.points_balance + coalesce(v_redemption.loyalty_spend, 0);
  v_tier := case when v_balance >= 1200 then 'Platinum'
    when v_balance >= 700 then 'Gold'
    when v_balance >= 300 then 'Silver'
    else 'Bronze' end;
  update loyaltymember set
    points_balance = v_balance, tier = v_tier,
    redemption_made = greatest(coalesce(redemption_made, 0) - 1, 0)
    where company_id = p_company_id and loyalty_id = v_redemption.loyalty_id;
  update redemption set
    status = 'Cancelled', cancelled_date = current_date,
    cancelled_time = localtime, cancellation_reason = btrim(p_reason)
    where company_id = p_company_id and redemption_id = p_redemption_id;
  update payment set redemption_id = null
    where company_id = p_company_id and payment_id = v_payment.payment_id;
  return jsonb_build_object(
    'redemption_id', p_redemption_id, 'status', 'Cancelled',
    'points_returned', coalesce(v_redemption.loyalty_spend, 0),
    'new_points_balance', v_balance
  );
end;
$$;

revoke all on function cancel_approved_redemption(int, int, text) from public, anon, authenticated;
grant execute on function cancel_approved_redemption(int, int, text) to service_role;
