-- ============================================================================
-- FIX: missing auto-increment on primary key columns
-- ============================================================================
-- Root cause: these 12 tables were created without an identity/auto-increment
-- default on their integer primary key column (this happens when a table is
-- created via CSV import in the Supabase Table Editor rather than through
-- the "New Table" UI, which sets this up automatically — that's why
-- `companies`/`accounts` already work fine and these don't).
--
-- Symptom: every "Create" action in the app (add customer, add pet, add
-- staff, add loyalty rule, apply leave, add booking, verify payment) fails
-- with: null value in column "<x>_id" of relation "<table>" violates
-- not-null constraint — because the backend deliberately omits the ID field
-- and expects Postgres to assign it, but nothing is configured to do that.
--
-- This migration converts each ID column to GENERATED BY DEFAULT AS IDENTITY,
-- seeded to start right after your current highest ID, so it will never
-- collide with your existing 540 bookings/payments, 20 customers/pets, etc.
-- Existing rows and their IDs are completely untouched — this only affects
-- how *future* inserts get their ID.
--
-- Run this once in the Supabase SQL Editor (Dashboard → SQL Editor → New query).
-- ============================================================================

alter table customer          alter column customer_id           add generated by default as identity (start with 21);
alter table pet                alter column pet_id                add generated by default as identity (start with 21);
alter table staff              alter column staff_id              add generated by default as identity (start with 6);
alter table coupon             alter column coupon_id             add generated by default as identity (start with 9);
alter table leave              alter column leave_id              add generated by default as identity (start with 9);
alter table grooming_booking   alter column grooming_booking_id   add generated by default as identity (start with 181);
alter table daycare_booking    alter column daycare_booking_id    add generated by default as identity (start with 181);
alter table boarding_booking   alter column boarding_booking_id   add generated by default as identity (start with 181);
alter table payment            alter column payment_id            add generated by default as identity (start with 541);
alter table redemption         alter column redemption_id         add generated by default as identity (start with 541);
alter table messages           alter column message_id            add generated by default as identity (start with 37);
alter table loyaltymember      alter column loyalty_id            add generated by default as identity (start with 18);
