-- Add database-generated IDs to tables that were originally imported from CSV.
--
-- This version is intentionally idempotent: it skips columns that already
-- have an identity and advances every identity sequence to the current
-- maximum value.  Application code must never generate IDs with max(id)+1;
-- concurrent inserts would otherwise select the same value.

do $$
declare
  item record;
  identity_kind "char";
  column_default text;
  sequence_name text;
  max_id bigint;
begin
  for item in
    select *
    from (values
      ('customer', 'customer_id'),
      ('pet', 'pet_id'),
      ('staff', 'staff_id'),
      ('coupon', 'coupon_id'),
      ('leave', 'leave_id'),
      ('grooming_booking', 'grooming_booking_id'),
      ('daycare_booking', 'daycare_booking_id'),
      ('boarding_booking', 'boarding_booking_id'),
      ('payment', 'payment_id'),
      ('redemption', 'redemption_id'),
      ('messages', 'message_id'),
      ('loyaltymember', 'loyalty_id')
    ) as ids(table_name, column_name)
  loop
    select a.attidentity, pg_get_expr(d.adbin, d.adrelid)
      into identity_kind, column_default
    from pg_attribute a
    left join pg_attrdef d
      on d.adrelid = a.attrelid and d.adnum = a.attnum
    where a.attrelid = format('public.%I', item.table_name)::regclass
      and a.attname = item.column_name
      and not a.attisdropped;

    if coalesce(identity_kind, '') = '' and column_default is null then
      execute format(
        'alter table public.%I alter column %I add generated by default as identity',
        item.table_name,
        item.column_name
      );
    elsif coalesce(identity_kind, '') = '' and column_default not like 'nextval(%' then
      raise exception 'public.%.% has a non-sequence default (%)',
        item.table_name, item.column_name, column_default;
    end if;

    sequence_name := pg_get_serial_sequence(
      format('public.%I', item.table_name),
      item.column_name
    );
    if sequence_name is null then
      raise exception 'No identity/serial sequence found for public.%.%',
        item.table_name, item.column_name;
    end if;
    execute format(
      'select max(%I)::bigint from public.%I',
      item.column_name,
      item.table_name
    ) into max_id;

    if max_id is null then
      perform setval(sequence_name::regclass, 1, false);
    else
      perform setval(sequence_name::regclass, max_id, true);
    end if;
  end loop;
end
$$;
